#!/usr/bin/env bash

if [[ "$BASH_SOURCE" != "$0" ]]; then
	echo "run this file, don't source it."
	return
fi

cd "$(dirname "$BASH_SOURCE")"
cd ..

kernel="$(uname -s | tr '[:upper:]' '[:lower:]')"

if [ "$kernel" = "darwin" ] && [ -z "$(which brew)" ]; then
	echo 'Detected darwin but homebrew not found, do you want to install it? (y/N)'

	read install_brew
	if [ "$install_brew" = "y" ]; then
		echo "Installing homebrew..."
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	fi
fi

source scripts/get-cfg-dir.sh

for module in "$@"; do
	if ! [[ -d "$module" ]]; then
		echo "Module '$module' not found."
		continue
	fi

	if [[ -f "scripts/symlink-paths/$module.txt" ]]; then
		while read src dst; do
			eval "source scripts/try_ln.sh \"$src\" \"$dst\""
		done <"scripts/symlink-paths/$module.txt"
	else
		source scripts/try_ln.sh "$module" "$XDG_CONFIG_HOME/$module"
	fi

	if [[ -f "scripts/install-scripts/$module.sh" ]]; then
		source "scripts/install-scripts/$module.sh"
	fi
	if [[ -f "scripts/install-scripts/$module-$kernel.sh" ]]; then
		source "scripts/install-scripts/$module-$kernel.sh"
	fi
done
